const EstadoPedido = Object.freeze({
    PENDIENTE_DE_PAGO: 'PENDIENTE_DE_PAGO',
    PAGADO: 'PAGADO',
    COTIZACION: 'COTIZACION',
    COTIZACION_APROBADA: 'COTIZACION_APROBADA',
    SENIADO: 'SENIADO',
    EN_DISENIO: 'EN_DISENIO',
    EN_PRODUCCION: 'EN_PRODUCCION',
    TERMINADO: 'TERMINADO',
    EN_PREPARACION: 'EN_PREPARACION',
    EN_DESPACHO: 'EN_DESPACHO',
    ENTREGADO: 'ENTREGADO'
});

export default EstadoPedido;
